[package]
name = "telecloud-transfer"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
telecloud-core = { workspace = true }
telecloud-manifest = { workspace = true }
telecloud-storage = { workspace = true }
telecloud-crypto = { workspace = true }
telecloud-db = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
futures = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
telecloud-integrity = { workspace = true }
