!macro NSIS_HOOK_POSTINSTALL
  CreateShortCut "$DESKTOP\TELEVAULT.lnk" "$INSTDIR\TELEVAULT.exe" "" "$INSTDIR\TELEVAULT.exe" 0
!macroend

!macro NSIS_HOOK_PREUNINSTALL
  Delete "$DESKTOP\TELEVAULT.lnk"
!macroend

