// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Returns application metadata and runtime diagnostic information. */
	getAppInfo: () => typedError<AppInfoDto, IpcError>(__TAURI_INVOKE("get_app_info")),
	/**  Returns the resolved canonical filesystem paths used by TELEVAULT. */
	getSystemPaths: () => typedError<SystemPathsDto, IpcError>(__TAURI_INVOKE("get_system_paths")),
	/**  Lists all configured backup profiles from the database. */
	listBackupProfiles: () => typedError<BackupProfileDto[], IpcError>(__TAURI_INVOKE("list_backup_profiles")),
	/**  Retrieves a specific backup profile by ProfileId. */
	getBackupProfile: (profileId: string) => typedError<BackupProfileDto, IpcError>(__TAURI_INVOKE("get_backup_profile", { profileId })),
	/**  Creates and persists a new backup profile. */
	createBackupProfile: (request: CreateProfileRequest) => typedError<BackupProfileDto, IpcError>(__TAURI_INVOKE("create_backup_profile", { request })),
	/**  Updates an existing backup profile. */
	updateBackupProfile: (request: UpdateProfileRequest) => typedError<BackupProfileDto, IpcError>(__TAURI_INVOKE("update_backup_profile", { request })),
	/**  Deletes a backup profile. */
	deleteBackupProfile: (profileId: string) => typedError<boolean, IpcError>(__TAURI_INVOKE("delete_backup_profile", { profileId })),
	/**
	 *  Initiates a point-in-time snapshot backup for the specified profile.
	 * 
	 *  Execution runs asynchronously offloaded to tokio worker threads to preserve UI responsiveness.
	 */
	startBackup: (request: StartBackupRequest) => typedError<BackupSummaryDto, IpcError>(__TAURI_INVOKE("start_backup", { request })),
	/**  Lists all historical snapshots for a backup profile. */
	listSnapshots: (profileId: string) => typedError<SnapshotDto[], IpcError>(__TAURI_INVOKE("list_snapshots", { profileId })),
	/**  Lists all files and version records belonging to a historical snapshot. */
	getSnapshotFiles: (snapshotId: string) => typedError<SnapshotFileDto[], IpcError>(__TAURI_INVOKE("get_snapshot_files", { snapshotId })),
	/**  Restores a backed-up logical file to a specified local destination path. */
	restoreFile: (request: RestoreFileRequest) => typedError<RestoreResultDto, IpcError>(__TAURI_INVOKE("restore_file", { request })),
	/**  Restores a logical file from a standalone Manifest V1 JSON string. */
	restoreManifest: (request: RestoreManifestRequest) => typedError<RestoreResultDto, IpcError>(__TAURI_INVOKE("restore_manifest", { request })),
	/**  Restores an entire historical snapshot hierarchy into a destination folder. */
	restoreSnapshot: (request: RestoreSnapshotRequest) => typedError<SnapshotRestoreResultDto, IpcError>(__TAURI_INVOKE("restore_snapshot", { request })),
	/**  Fast, metadata-only pre-validation for a manifest (zero full-payload download). */
	verifyManifestMetadata: (request: VerifyManifestRequest) => typedError<ManifestVerificationReportDto, IpcError>(__TAURI_INVOKE("verify_manifest_metadata", { request })),
	/**  Full end-to-end trial restore verification into temporary managed staging. */
	verifyFullRestore: (request: RestoreFileRequest) => typedError<FullVerificationReportDto, IpcError>(__TAURI_INVOKE("verify_full_restore", { request })),
	/**  Checks whether a specific relative path within a profile has been backed up. */
	checkFileStatus: (request: CheckFileStatusRequest) => typedError<FileStatusDto, IpcError>(__TAURI_INVOKE("check_file_status", { request })),
	/**  Checks if an incremental backup is needed for the given profile by comparing local scans against last snapshot. */
	isIncrementalBackupNeeded: (profileId: string) => typedError<boolean, IpcError>(__TAURI_INVOKE("is_incremental_backup_needed", { profileId })),
	/**  Lists all historical backed-up versions for a specific FileId. */
	getFileVersions: (fileId: string) => typedError<FileVersionDto[], IpcError>(__TAURI_INVOKE("get_file_versions", { fileId })),
	/**  Lists recent transfer jobs from the SQLite catalog. */
	listTransferJobs: (limit: number | null) => typedError<TransferJobDto[], IpcError>(__TAURI_INVOKE("list_transfer_jobs", { limit })),
	/**  Retrieves a specific transfer job record by JobId. */
	getTransferJob: (jobId: string) => typedError<TransferJobDto, IpcError>(__TAURI_INVOKE("get_transfer_job", { jobId })),
	/**  Queries aggregate counts across transfer queues. */
	getTransferStatus: () => typedError<TransferStatusDto, IpcError>(__TAURI_INVOKE("get_transfer_status")),
	/**  Cooperatively cancels an active operation (backup, restore, transfer) via its registered cancellation token. */
	cancelOperation: (request: CancelOperationRequest) => typedError<boolean, IpcError>(__TAURI_INVOKE("cancel_operation", { request })),
	/**  Lists all configured backup schedules. */
	listSchedules: () => typedError<ScheduleDto[], IpcError>(__TAURI_INVOKE("list_schedules")),
	/**  Retrieves a specific backup schedule by ID. */
	getSchedule: (scheduleId: string) => typedError<ScheduleDto, IpcError>(__TAURI_INVOKE("get_schedule", { scheduleId })),
	/**  Creates a new recurring backup schedule. */
	createSchedule: (request: CreateScheduleRequest) => typedError<ScheduleDto, IpcError>(__TAURI_INVOKE("create_schedule", { request })),
	/**  Updates an existing backup schedule's expression or timing. */
	updateSchedule: (request: UpdateScheduleRequest) => typedError<ScheduleDto, IpcError>(__TAURI_INVOKE("update_schedule", { request })),
	/**  Deletes a backup schedule by its unique ID. */
	deleteSchedule: (scheduleId: string) => typedError<boolean, IpcError>(__TAURI_INVOKE("delete_schedule", { scheduleId })),
	/**  Enables a schedule and recalculates its next execution time. */
	enableSchedule: (scheduleId: string) => typedError<ScheduleDto, IpcError>(__TAURI_INVOKE("enable_schedule", { scheduleId })),
	/**  Disables a schedule and cancels pending executions. */
	disableSchedule: (scheduleId: string) => typedError<ScheduleDto, IpcError>(__TAURI_INVOKE("disable_schedule", { scheduleId })),
	/**  Triggers an immediate execution of a scheduled backup. */
	runScheduleNow: (scheduleId: string) => typedError<string | null, IpcError>(__TAURI_INVOKE("run_schedule_now", { scheduleId })),
	/**  Queries current operational status and active workers of the scheduler. */
	getSchedulerStatus: () => typedError<SchedulerStatusDto, IpcError>(__TAURI_INVOKE("get_scheduler_status")),
	/**  Retrieves execution history for a schedule. */
	getScheduleHistory: (scheduleId: string, limit: number | null) => typedError<ScheduleHistoryDto[], IpcError>(__TAURI_INVOKE("get_schedule_history", { scheduleId, limit })),
};

/* Types */
/**  Diagnostic metadata describing the running TELEVAULT application instance. */
export type AppInfoDto = {
	/**  Canonical application name. */
	app_name: string,
	/**  Semantic version of the build. */
	version: string,
	/**  Operating system platform. */
	platform: string,
	/**  Architecture indicator. */
	arch: string,
	/**  Release or debug build mode. */
	build_mode: string,
};

/**  Stable DTO representing a configured backup profile. */
export type BackupProfileDto = {
	profile_id: string,
	name: string,
	description: string | null,
	source_path: string,
	enabled: boolean,
	created_at: string,
	updated_at: string,
};

/**  Summary results of an executed backup operation. */
export type BackupSummaryDto = {
	snapshot_id: string,
	profile_id: string,
	status: string,
	new_files: number,
	modified_files: number,
	unchanged_files: number,
	deleted_files: number,
	transferred_chunks: number,
	transferred_bytes: number,
	reused_bytes: number,
	elapsed_ms: number,
	error_message: string | null,
};

/**  Request to cooperatively cancel an active operation (backup, restore, transfer). */
export type CancelOperationRequest = {
	/**  Identifier of the operation to cancel (e.g. JobId, ProfileId, SnapshotId). */
	operation_id: string,
};

/**  Request to query backup status of a specific local file within a profile. */
export type CheckFileStatusRequest = {
	/**  Profile identifier owning the file. */
	profile_id: string,
	/**  Relative path within the profile directory. */
	relative_path: string,
};

/**  Policy for handling existing target files at destination during restore. */
export type CollisionPolicyDto = 
/**  Replace the existing file with the restored payload. */
"overwrite" | 
/**  Skip restoring without modifying the existing file. */
"skip" | 
/**  Keep both by generating a deterministic alternate filename (e.g. "doc (1).txt"). */
"keep_both";

/**  Frontend request to register a new backup profile. */
export type CreateProfileRequest = {
	/**  Unique profile identifier (e.g. "prof-docs"). */
	profile_id: string,
	/**  Human-friendly display label (e.g. "Work Documents"). */
	name: string,
	/**  Optional description. */
	description: string | null,
	/**  Absolute local filesystem path to the folder to back up. */
	source_path: string,
};

/**  Parameters for creating a new recurring backup schedule. */
export type CreateScheduleRequest = {
	/**  Target backup profile identifier. */
	profile_id: string,
	/**  Schedule type: 'interval', 'daily', 'weekly', 'cron'. */
	schedule_type: string,
	/**  Recurrence expression (e.g. "15m", "02:00", "Sun@03:00", "0 2 * * *"). */
	expression: string,
	/**  Timezone strategy: 'local' (default) or 'utc'. */
	timezone: string | null,
	/**  Whether the schedule is active upon creation. */
	enabled: boolean | null,
};

/**  Resulting outcome of a file restore operation. */
export type FileRestoreOutcomeDto = "restored" | "overwritten" | "skipped" | "kept_both" | "cancelled" | "failed";

/**  Status report indicating whether a file is backed up and needs incremental upload. */
export type FileStatusDto = {
	profile_id: string,
	relative_path: string,
	is_backed_up: boolean,
	file_id: string | null,
	latest_version_id: string | null,
	incremental_needed: boolean,
};

/**  Historical version record for a backed-up file. */
export type FileVersionDto = {
	version_id: string,
	file_id: string,
	snapshot_id: string,
	manifest_id: string,
	status: string,
	created_at: string,
};

/**  Full end-to-end trial restore verification report. */
export type FullVerificationReportDto = {
	file_id: string,
	verified: boolean,
	sha256_match: boolean,
	size_match: boolean,
	duration_ms: number,
	error: string | null,
};

/**
 *  Universal structured error DTO returned across the Tauri IPC boundary.
 * 
 *  Ensures stable, typed error codes for React to branch upon without parsing English strings.
 *  Secrets, keys, and raw internal panic messages are strictly excluded.
 */
export type IpcError = {
	/**  Stable machine-readable error code (e.g. "VALIDATION_ERROR", "NOT_FOUND"). */
	code: string,
	/**  Human-readable diagnostic description safe for UI presentation. */
	message: string,
	/**  Optional contextual detail (e.g. affected identifier or field name). */
	details: string | null,
};

/**  Lightweight fast metadata verification report (zero full payload download). */
export type ManifestVerificationReportDto = {
	file_id: string,
	relative_path: string,
	is_restorable: boolean,
	total_chunks: number,
	original_size: number,
	remote_objects_verified: boolean,
	issues: string[],
};

/**  Request to restore a specific logical file by FileId. */
export type RestoreFileRequest = {
	/**  File identifier to restore. */
	file_id: string,
	/**  Target local filesystem destination path. */
	destination_path: string,
	/**  Collision policy if target already exists. */
	collision_policy: CollisionPolicyDto,
	/**  Optional decryption passphrase if file was encrypted. */
	passphrase: string | null,
};

/**  Request to restore from an arbitrary standalone Manifest JSON string. */
export type RestoreManifestRequest = {
	/**  Raw Manifest V1 JSON string. */
	manifest_json: string,
	/**  Target local filesystem destination path. */
	destination_path: string,
	/**  Collision policy if target already exists. */
	collision_policy: CollisionPolicyDto,
	/**  Optional decryption passphrase if file was encrypted. */
	passphrase: string | null,
};

/**  Result details of an individual file restore operation. */
export type RestoreResultDto = {
	file_id: string,
	target_path: string,
	bytes_restored: number,
	duration_ms: number,
	outcome: FileRestoreOutcomeDto,
};

/**  Request to restore an entire historical snapshot folder tree. */
export type RestoreSnapshotRequest = {
	/**  Snapshot identifier to restore. */
	snapshot_id: string,
	/**  Root local directory where snapshot files will be reassembled. */
	destination_directory: string,
	/**  Collision policy if destination files already exist. */
	collision_policy: CollisionPolicyDto,
	/**  Optional decryption passphrase if snapshot contains encrypted files. */
	passphrase: string | null,
};

/**  User-facing representation of a recurring backup schedule. */
export type ScheduleDto = {
	/**  Unique schedule identifier. */
	schedule_id: string,
	/**  Associated backup profile identifier. */
	profile_id: string,
	/**  Schedule recurrence type. */
	schedule_type: string,
	/**  Schedule expression string. */
	expression: string,
	/**  Timezone calculation strategy. */
	timezone: string,
	/**  Whether the schedule is currently enabled. */
	enabled: boolean,
	/**  ISO-8601 UTC timestamp of next scheduled execution. */
	next_run_at: string | null,
	/**  ISO-8601 UTC timestamp of last executed run. */
	last_run_at: string | null,
	/**  Execution status from the last run. */
	last_status: string | null,
	/**  Error code if the last run failed. */
	last_error_code: string | null,
	/**  Schedule creation timestamp. */
	created_at: string,
	/**  Schedule last update timestamp. */
	updated_at: string,
};

/**  Execution history record for a scheduled backup run. */
export type ScheduleHistoryDto = {
	/**  Unique execution history record identifier. */
	history_id: string,
	/**  Associated schedule identifier. */
	schedule_id: string,
	/**  Associated profile identifier. */
	profile_id: string,
	/**  Execution start timestamp. */
	started_at: string,
	/**  Execution completion timestamp, if finished. */
	completed_at: string | null,
	/**  Execution status ('completed', 'failed', 'cancelled', 'skipped'). */
	status: string,
	/**  Snapshot identifier if backup completed. */
	snapshot_id: string | null,
	/**  Total files processed. */
	files_processed: number,
	/**  Total payload bytes transferred. */
	bytes_transferred: number,
	/**  Error code if execution failed. */
	error_code: string | null,
	/**  Safe human-readable error message. */
	error_message: string | null,
};

/**  Overall status and health of the scheduler subsystem. */
export type SchedulerStatusDto = {
	/**  Operational status: 'running', 'stopped', 'paused'. */
	status: string,
	/**  Number of configured enabled schedules. */
	active_schedules_count: number,
	/**  Profiles currently executing backups. */
	running_profiles: string[],
};

/**  Historical snapshot metadata record. */
export type SnapshotDto = {
	snapshot_id: string,
	profile_id: string,
	status: string,
	metadata: string | null,
	created_at: string,
};

/**  File item within a specific historical snapshot. */
export type SnapshotFileDto = {
	file_id: string,
	relative_path: string,
	size_bytes: number,
	status: string,
	mime_type: string | null,
};

/**  Result details of a full snapshot directory restore operation. */
export type SnapshotRestoreResultDto = {
	snapshot_id: string,
	target_directory: string,
	total_files: number,
	restored_files: number,
	skipped_files: number,
	failed_files: number,
	total_bytes: number,
	duration_ms: number,
};

/**  Request to initiate a point-in-time snapshot backup for a profile. */
export type StartBackupRequest = {
	/**  Profile identifier to back up. */
	profile_id: string,
	/**  Optional encryption passphrase if profile has encryption enabled. */
	passphrase: string | null,
};

/**  Standardized resolved system directories managed by PathManager. */
export type SystemPathsDto = {
	/**  Root data directory (e.g. %LOCALAPPDATA%\TELEVAULT). */
	base_dir: string,
	/**  Path to embedded SQLite database. */
	database_path: string,
	/**  Path to temporary payload staging directory. */
	temp_dir: string,
	/**  Path to application logs directory. */
	logs_dir: string,
	/**  Path to application config directory. */
	config_dir: string,
};

/**  Snapshot of a transfer job record. */
export type TransferJobDto = {
	job_id: string,
	file_id: string,
	chunk_id: string | null,
	direction: string,
	status: string,
	progress: number,
	retry_count: number,
	error_message: string | null,
	created_at: string,
	updated_at: string,
};

/**  Aggregate summary of transfer engine queues. */
export type TransferStatusDto = {
	active_count: number,
	queued_count: number,
	completed_count: number,
	failed_count: number,
};

/**  Frontend request to modify an existing backup profile. */
export type UpdateProfileRequest = {
	/**  Identifier of the profile to update. */
	profile_id: string,
	/**  New human-friendly label if modifying. */
	name: string | null,
	/**  Optional description if modifying. */
	description: string | null,
	/**  New source directory path if modifying. */
	source_path: string | null,
	/**  Enable or disable profile. */
	enabled: boolean | null,
};

/**  Parameters for updating an existing schedule configuration. */
export type UpdateScheduleRequest = {
	/**  Target schedule identifier. */
	schedule_id: string,
	/**  New schedule type, if updating. */
	schedule_type: string | null,
	/**  New recurrence expression, if updating. */
	expression: string | null,
	/**  New timezone strategy, if updating. */
	timezone: string | null,
	/**  New enabled state, if updating. */
	enabled: boolean | null,
};

/**  Request to verify metadata of a manifest by FileId. */
export type VerifyManifestRequest = {
	file_id: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

