// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Returns application metadata and runtime diagnostic information. */
	getAppInfo: () => typedError<AppInfoDto, IpcError>(__TAURI_INVOKE("get_app_info")),
	/**  Returns the resolved canonical filesystem paths used by TELEVAULT. */
	getSystemPaths: () => typedError<SystemPathsDto, IpcError>(__TAURI_INVOKE("get_system_paths")),
	/**  Returns the current application configuration preferences from disk or default. */
	getAppConfig: () => typedError<AppConfigDto, IpcError>(__TAURI_INVOKE("get_app_config")),
	/**  Validates, persists, and returns updated application configuration preferences. */
	updateAppConfig: (request: AppConfigDto) => typedError<AppConfigDto, IpcError>(__TAURI_INVOKE("update_app_config", { request })),
	/**  Lists all configured backup profiles from the database. */
	listBackupProfiles: () => typedError<BackupProfileDto[], IpcError>(__TAURI_INVOKE("list_backup_profiles")),
	/**  Retrieves a specific backup profile by ProfileId. */
	getBackupProfile: (profileId: string) => typedError<BackupProfileDto, IpcError>(__TAURI_INVOKE("get_backup_profile", { profileId })),
	/**  Creates and persists a new backup profile. */
	createBackupProfile: (request: CreateProfileRequest) => typedError<BackupProfileDto, IpcError>(__TAURI_INVOKE("create_backup_profile", { request })),
	/**  Updates an existing backup profile. */
	updateBackupProfile: (request: UpdateProfileRequest) => typedError<BackupProfileDto, IpcError>(__TAURI_INVOKE("update_backup_profile", { request })),
	/**  Deletes a backup profile. */
	deleteBackupProfile: (profileId: string) => typedError<boolean, IpcError>(__TAURI_INVOKE("delete_backup_profile", { profileId })),
	/**
	 *  Initiates a point-in-time snapshot backup for the specified profile.
	 * 
	 *  Execution runs asynchronously offloaded to tokio worker threads to preserve UI responsiveness.
	 */
	startBackup: (request: StartBackupRequest) => typedError<BackupSummaryDto, IpcError>(__TAURI_INVOKE("start_backup", { request })),
	/**  Lists all historical snapshots for a backup profile. */
	listSnapshots: (profileId: string) => typedError<SnapshotDto[], IpcError>(__TAURI_INVOKE("list_snapshots", { profileId })),
	/**  Lists all files and version records belonging to a historical snapshot. */
	getSnapshotFiles: (snapshotId: string) => typedError<SnapshotFileDto[], IpcError>(__TAURI_INVOKE("get_snapshot_files", { snapshotId })),
	/**  Restores a backed-up logical file to a specified local destination path. */
	restoreFile: (request: RestoreFileRequest) => typedError<RestoreResultDto, IpcError>(__TAURI_INVOKE("restore_file", { request })),
	/**  Restores a logical file from a standalone Manifest V1 JSON string. */
	restoreManifest: (request: RestoreManifestRequest) => typedError<RestoreResultDto, IpcError>(__TAURI_INVOKE("restore_manifest", { request })),
	/**  Restores an entire historical snapshot hierarchy into a destination folder. */
	restoreSnapshot: (request: RestoreSnapshotRequest) => typedError<SnapshotRestoreResultDto, IpcError>(__TAURI_INVOKE("restore_snapshot", { request })),
	/**  Fast, metadata-only pre-validation for a manifest (zero full-payload download). */
	verifyManifestMetadata: (request: VerifyManifestRequest) => typedError<ManifestVerificationReportDto, IpcError>(__TAURI_INVOKE("verify_manifest_metadata", { request })),
	/**  Full end-to-end trial restore verification into temporary managed staging. */
	verifyFullRestore: (request: RestoreFileRequest) => typedError<FullVerificationReportDto, IpcError>(__TAURI_INVOKE("verify_full_restore", { request })),
	/**  Checks whether a specific relative path within a profile has been backed up. */
	checkFileStatus: (request: CheckFileStatusRequest) => typedError<FileStatusDto, IpcError>(__TAURI_INVOKE("check_file_status", { request })),
	/**  Checks if an incremental backup is needed for the given profile by comparing local scans against last snapshot. */
	isIncrementalBackupNeeded: (profileId: string) => typedError<boolean, IpcError>(__TAURI_INVOKE("is_incremental_backup_needed", { profileId })),
	/**  Lists all historical backed-up versions for a specific FileId. */
	getFileVersions: (fileId: string) => typedError<FileVersionDto[], IpcError>(__TAURI_INVOKE("get_file_versions", { fileId })),
	/**  Lists recent transfer jobs from the SQLite catalog. */
	listTransferJobs: (limit: number | null) => typedError<TransferJobDto[], IpcError>(__TAURI_INVOKE("list_transfer_jobs", { limit })),
	/**  Retrieves a specific transfer job record by JobId. */
	getTransferJob: (jobId: string) => typedError<TransferJobDto, IpcError>(__TAURI_INVOKE("get_transfer_job", { jobId })),
	/**  Queries aggregate counts across transfer queues. */
	getTransferStatus: () => typedError<TransferStatusDto, IpcError>(__TAURI_INVOKE("get_transfer_status")),
	/**  Cooperatively cancels an active operation (backup, restore, transfer) via its registered cancellation token. */
	cancelOperation: (request: CancelOperationRequest) => typedError<boolean, IpcError>(__TAURI_INVOKE("cancel_operation", { request })),
	/**  Lists all configured backup schedules. */
	listSchedules: () => typedError<ScheduleDto[], IpcError>(__TAURI_INVOKE("list_schedules")),
	/**  Retrieves a specific backup schedule by ID. */
	getSchedule: (scheduleId: string) => typedError<ScheduleDto, IpcError>(__TAURI_INVOKE("get_schedule", { scheduleId })),
	/**  Creates a new recurring backup schedule. */
	createSchedule: (request: CreateScheduleRequest) => typedError<ScheduleDto, IpcError>(__TAURI_INVOKE("create_schedule", { request })),
	/**  Updates an existing backup schedule's expression or timing. */
	updateSchedule: (request: UpdateScheduleRequest) => typedError<ScheduleDto, IpcError>(__TAURI_INVOKE("update_schedule", { request })),
	/**  Deletes a backup schedule by its unique ID. */
	deleteSchedule: (scheduleId: string) => typedError<boolean, IpcError>(__TAURI_INVOKE("delete_schedule", { scheduleId })),
	/**  Enables a schedule and recalculates its next execution time. */
	enableSchedule: (scheduleId: string) => typedError<ScheduleDto, IpcError>(__TAURI_INVOKE("enable_schedule", { scheduleId })),
	/**  Disables a schedule and cancels pending executions. */
	disableSchedule: (scheduleId: string) => typedError<ScheduleDto, IpcError>(__TAURI_INVOKE("disable_schedule", { scheduleId })),
	/**  Triggers an immediate execution of a scheduled backup. */
	runScheduleNow: (scheduleId: string) => typedError<string | null, IpcError>(__TAURI_INVOKE("run_schedule_now", { scheduleId })),
	/**  Queries current operational status and active workers of the scheduler. */
	getSchedulerStatus: () => typedError<SchedulerStatusDto, IpcError>(__TAURI_INVOKE("get_scheduler_status")),
	/**  Retrieves execution history for a schedule. */
	getScheduleHistory: (scheduleId: string, limit: number | null) => typedError<ScheduleHistoryDto[], IpcError>(__TAURI_INVOKE("get_schedule_history", { scheduleId, limit })),
	/**  Retrieves the configured retention policy for a backup profile. */
	getRetentionPolicy: (profileId: string) => typedError<RetentionPolicyDto, IpcError>(__TAURI_INVOKE("get_retention_policy", { profileId })),
	/**  Updates and persists the retention policy configuration for a profile. */
	setRetentionPolicy: (request: SetRetentionPolicyRequest) => typedError<RetentionPolicyDto, IpcError>(__TAURI_INVOKE("set_retention_policy", { request })),
	/**  Previews retention policy evaluation (dry-run) without modifying database records. */
	previewRetention: (profileId: string) => typedError<RetentionEvaluationDto, IpcError>(__TAURI_INVOKE("preview_retention", { profileId })),
	/**  Executes retention pruning on local metadata for a profile. */
	executeRetention: (profileId: string) => typedError<RetentionResultDto, IpcError>(__TAURI_INVOKE("execute_retention", { profileId })),
	/**  Retrieves retention execution audit history for a profile. */
	getRetentionHistory: (profileId: string, limit: number | null) => typedError<RetentionHistoryDto[], IpcError>(__TAURI_INVOKE("get_retention_history", { profileId, limit })),
	/**  Verifies a tracked file in a profile by auditing its latest backup manifest and chunks. */
	verifyFileBackup: (request: VerifyTargetRequest) => typedError<VerificationResultDto, IpcError>(__TAURI_INVOKE("verify_file_backup", { request })),
	/**  Verifies a specific backup manifest record by its manifest identifier. */
	verifyManifest: (request: VerifyTargetRequest) => typedError<VerificationResultDto, IpcError>(__TAURI_INVOKE("verify_manifest", { request })),
	/**  Verifies all file manifests comprising an entire snapshot. */
	verifySnapshot: (request: VerifyTargetRequest) => typedError<VerificationResultDto, IpcError>(__TAURI_INVOKE("verify_snapshot", { request })),
	/**  Verifies all tracked files and snapshots across an entire backup profile. */
	verifyProfile: (request: VerifyTargetRequest) => typedError<VerificationResultDto, IpcError>(__TAURI_INVOKE("verify_profile", { request })),
	/**  Retrieves persisted historical verification records for a profile. */
	getVerificationHistory: (profileId: string, limit: number | null) => typedError<VerificationHistoryRecordDto[], IpcError>(__TAURI_INVOKE("get_verification_history", { profileId, limit })),
	/**  Generates a preview analysis of needed repairs without mutating remote or local state. */
	previewRepair: (request: PreviewRepairRequest) => typedError<RepairPreviewDto, IpcError>(__TAURI_INVOKE("preview_repair", { request })),
	/**  Executes remote repair for an individual logical file. */
	repairFile: (request: RepairFileRequest) => typedError<RepairExecutionResultDto, IpcError>(__TAURI_INVOKE("repair_file", { request })),
	/**  Executes remote repair across all files in a backup snapshot. */
	repairSnapshot: (request: RepairSnapshotRequest) => typedError<RepairExecutionResultDto, IpcError>(__TAURI_INVOKE("repair_snapshot", { request })),
	/**  Lists remote repair history records for a profile, ordered newest first. */
	getRepairHistory: (profileId: string, limit: number | null) => typedError<RepairHistoryRecordDto[], IpcError>(__TAURI_INVOKE("get_repair_history", { profileId, limit })),
};

/* Types */
/**  Full application configuration DTO reflecting the validated AppConfig model. */
export type AppConfigDto = {
	/**  General UI and update preferences. */
	general: GeneralConfigDto,
	/**  Storage cache and retention limits. */
	storage: StorageConfigDto,
	/**  Transfer worker concurrency and chunk settings. */
	transfer: TransferConfigDto,
	/**  Default backup engine preferences. */
	backup: BackupPreferencesDto,
};

/**  Diagnostic metadata describing the running TELEVAULT application instance. */
export type AppInfoDto = {
	/**  Canonical application name. */
	app_name: string,
	/**  Semantic version of the build. */
	version: string,
	/**  Operating system platform. */
	platform: string,
	/**  Architecture indicator. */
	arch: string,
	/**  Release or debug build mode. */
	build_mode: string,
};

/**  Default backup preferences for profiles. */
export type BackupPreferencesDto = {
	/**  Default compression algorithm ("None" or "Zstd"). */
	default_compression: string,
	/**  Default snapshot retention period in days (0 = keep indefinitely). */
	retention_days: number,
	/**  Whether to verify cryptographic hashes immediately following backup upload. */
	verify_after_backup: boolean,
};

/**  Stable DTO representing a configured backup profile. */
export type BackupProfileDto = {
	profile_id: string,
	name: string,
	description: string | null,
	source_path: string,
	enabled: boolean,
	created_at: string,
	updated_at: string,
};

/**  Summary results of an executed backup operation. */
export type BackupSummaryDto = {
	snapshot_id: string,
	profile_id: string,
	status: string,
	new_files: number,
	modified_files: number,
	unchanged_files: number,
	deleted_files: number,
	transferred_chunks: number,
	transferred_bytes: number,
	reused_bytes: number,
	elapsed_ms: number,
	error_message: string | null,
};

/**  Request to cooperatively cancel an active operation (backup, restore, transfer). */
export type CancelOperationRequest = {
	/**  Identifier of the operation to cancel (e.g. JobId, ProfileId, SnapshotId). */
	operation_id: string,
};

/**  Request to query backup status of a specific local file within a profile. */
export type CheckFileStatusRequest = {
	/**  Profile identifier owning the file. */
	profile_id: string,
	/**  Relative path within the profile directory. */
	relative_path: string,
};

/**  Policy for handling existing target files at destination during restore. */
export type CollisionPolicyDto = 
/**  Replace the existing file with the restored payload. */
"overwrite" | 
/**  Skip restoring without modifying the existing file. */
"skip" | 
/**  Keep both by generating a deterministic alternate filename (e.g. "doc (1).txt"). */
"keep_both";

/**  Frontend request to register a new backup profile. */
export type CreateProfileRequest = {
	/**  Unique profile identifier (e.g. "prof-docs"). */
	profile_id: string,
	/**  Human-friendly display label (e.g. "Work Documents"). */
	name: string,
	/**  Optional description. */
	description: string | null,
	/**  Absolute local filesystem path to the folder to back up. */
	source_path: string,
};

/**  Parameters for creating a new recurring backup schedule. */
export type CreateScheduleRequest = {
	/**  Target backup profile identifier. */
	profile_id: string,
	/**  Schedule type: 'interval', 'daily', 'weekly', 'cron'. */
	schedule_type: string,
	/**  Recurrence expression (e.g. "15m", "02:00", "Sun@03:00", "0 2 * * *"). */
	expression: string,
	/**  Timezone strategy: 'local' (default) or 'utc'. */
	timezone: string | null,
	/**  Whether the schedule is active upon creation. */
	enabled: boolean | null,
};

/**  Resulting outcome of a file restore operation. */
export type FileRestoreOutcomeDto = "restored" | "overwritten" | "skipped" | "kept_both" | "cancelled" | "failed";

/**  Status report indicating whether a file is backed up and needs incremental upload. */
export type FileStatusDto = {
	profile_id: string,
	relative_path: string,
	is_backed_up: boolean,
	file_id: string | null,
	latest_version_id: string | null,
	incremental_needed: boolean,
};

/**  Historical version record for a backed-up file. */
export type FileVersionDto = {
	version_id: string,
	file_id: string,
	snapshot_id: string,
	manifest_id: string,
	status: string,
	created_at: string,
};

/**  Full end-to-end trial restore verification report. */
export type FullVerificationReportDto = {
	file_id: string,
	verified: boolean,
	sha256_match: boolean,
	size_match: boolean,
	duration_ms: number,
	error: string | null,
};

/**  General application user interface preferences. */
export type GeneralConfigDto = {
	/**  Visual theme ("dark", "light", "system"). */
	theme: string,
	/**  UI language code (e.g. "en-US"). */
	language: string,
	/**  Whether automatic update check is active. */
	check_updates: boolean,
};

/**
 *  Universal structured error DTO returned across the Tauri IPC boundary.
 * 
 *  Ensures stable, typed error codes for React to branch upon without parsing English strings.
 *  Secrets, keys, and raw internal panic messages are strictly excluded.
 */
export type IpcError = {
	/**  Stable machine-readable error code (e.g. "VALIDATION_ERROR", "NOT_FOUND"). */
	code: string,
	/**  Human-readable diagnostic description safe for UI presentation. */
	message: string,
	/**  Optional contextual detail (e.g. affected identifier or field name). */
	details: string | null,
};

/**  Lightweight fast metadata verification report (zero full payload download). */
export type ManifestVerificationReportDto = {
	file_id: string,
	relative_path: string,
	is_restorable: boolean,
	total_chunks: number,
	original_size: number,
	remote_objects_verified: boolean,
	issues: string[],
};

/**  Request parameters for generating a repair preview. */
export type PreviewRepairRequest = {
	/**  Associated profile identifier enforcing ownership isolation. */
	profile_id: string,
	/**  Target type ("file" or "snapshot"). */
	target_type: string,
	/**  Target identifier (file_id or snapshot_id). */
	target_id: string,
	/**  Optional passphrase for encrypted backups. */
	passphrase: string | null,
	/**  Optional operation tracking identifier for cooperative cancellation. */
	operation_id: string | null,
};

/**  Data transfer object representing an individual chunk candidate for repair. */
export type RepairCandidateDto = {
	chunk_id: string,
	chunk_index: number,
	total_chunks: number,
	finding_code: string,
	old_storage_reference: string,
	plaintext_size: number,
	stored_size: number,
	source_path: string,
};

/**  Data transfer object representing the repair result of an individual chunk. */
export type RepairChunkResultDto = {
	chunk_id: string,
	chunk_index: number,
	status: string,
	old_storage_reference: string,
	new_storage_reference: string | null,
	bytes_processed: number,
	duration_ms: number,
	error: string | null,
};

/**  Data transfer object representing the overall repair execution outcome. */
export type RepairExecutionResultDto = {
	profile_id: string,
	target_type: string,
	target_id: string,
	total_chunks_evaluated: number,
	repaired_chunks: number,
	skipped_healthy_chunks: number,
	failed_chunks: number,
	total_bytes_transferred: number,
	duration_ms: number,
	chunk_results: RepairChunkResultDto[],
};

/**  Request parameters for repairing an individual logical file. */
export type RepairFileRequest = {
	/**  Associated profile identifier enforcing ownership isolation. */
	profile_id: string,
	/**  Logical file identifier to repair. */
	file_id: string,
	/**  Whether to perform dry-run evaluation without remote upload. */
	dry_run: boolean | null,
	/**  Optional passphrase for encrypted backups. */
	passphrase: string | null,
	/**  Optional operation tracking identifier for cooperative cancellation. */
	operation_id: string | null,
};

/**  Data transfer object representing an auditable repair history record. */
export type RepairHistoryRecordDto = {
	repair_id: string,
	profile_id: string,
	snapshot_id: string | null,
	file_id: string,
	manifest_id: string,
	chunk_id: string,
	chunk_index: number,
	repair_type: string,
	finding_code: string,
	old_storage_reference: string,
	new_storage_reference: string,
	status: string,
	bytes_processed: number,
	duration_ms: number,
	error_message: string | null,
	repaired_at: string,
};

/**  Data transfer object representing preview analysis prior to repair. */
export type RepairPreviewDto = {
	profile_id: string,
	target_type: string,
	target_id: string,
	eligible_candidates: RepairCandidateDto[],
	ineligible_findings_count: number,
	total_affected_chunks: number,
	total_estimated_bytes: number,
	is_repairable: boolean,
};

/**  Request parameters for repairing an entire backup snapshot. */
export type RepairSnapshotRequest = {
	/**  Associated profile identifier enforcing ownership isolation. */
	profile_id: string,
	/**  Snapshot identifier to repair. */
	snapshot_id: string,
	/**  Whether to perform dry-run evaluation without remote upload. */
	dry_run: boolean | null,
	/**  Optional passphrase for encrypted backups. */
	passphrase: string | null,
	/**  Optional operation tracking identifier for cooperative cancellation. */
	operation_id: string | null,
};

/**  Request to restore a specific logical file by FileId. */
export type RestoreFileRequest = {
	/**  File identifier to restore. */
	file_id: string,
	/**  Target local filesystem destination path. */
	destination_path: string,
	/**  Collision policy if target already exists. */
	collision_policy: CollisionPolicyDto,
	/**  Optional decryption passphrase if file was encrypted. */
	passphrase: string | null,
};

/**  Request to restore from an arbitrary standalone Manifest JSON string. */
export type RestoreManifestRequest = {
	/**  Raw Manifest V1 JSON string. */
	manifest_json: string,
	/**  Target local filesystem destination path. */
	destination_path: string,
	/**  Collision policy if target already exists. */
	collision_policy: CollisionPolicyDto,
	/**  Optional decryption passphrase if file was encrypted. */
	passphrase: string | null,
};

/**  Result details of an individual file restore operation. */
export type RestoreResultDto = {
	file_id: string,
	target_path: string,
	bytes_restored: number,
	duration_ms: number,
	outcome: FileRestoreOutcomeDto,
};

/**  Request to restore an entire historical snapshot folder tree. */
export type RestoreSnapshotRequest = {
	/**  Snapshot identifier to restore. */
	snapshot_id: string,
	/**  Root local directory where snapshot files will be reassembled. */
	destination_directory: string,
	/**  Collision policy if destination files already exist. */
	collision_policy: CollisionPolicyDto,
	/**  Optional decryption passphrase if snapshot contains encrypted files. */
	passphrase: string | null,
};

/**  Retention decision for an individual snapshot. */
export type RetentionDecisionDto = {
	/**  Target snapshot identifier. */
	snapshot_id: string,
	/**  Action: 'KEEP' or 'PRUNE'. */
	action: string,
	/**  Explicit machine-readable reason (e.g. 'KEEP_LATEST', 'PRUNE_EXCESS_SNAPSHOT'). */
	reason: string,
	/**  Human-readable explanation. */
	description: string,
	/**  Snapshot execution status. */
	snapshot_status: string,
	/**  Snapshot creation timestamp (ISO-8601). */
	snapshot_created_at: string,
	/**  Calculated snapshot age in seconds. */
	age_secs: number,
	/**  Associated file versions count. */
	version_count: number,
};

/**  Deterministic evaluation report for a profile. */
export type RetentionEvaluationDto = {
	/**  Target backup profile identifier. */
	profile_id: string,
	/**  Timestamp when evaluation was computed. */
	evaluated_at: string,
	/**  Effective retention policy applied. */
	policy: RetentionPolicyDto,
	/**  Itemized decisions for each snapshot evaluated. */
	decisions: RetentionDecisionDto[],
	/**  Total snapshots evaluated. */
	snapshots_evaluated: number,
	/**  Total snapshots determined to KEEP. */
	snapshots_kept: number,
	/**  Total snapshots determined to PRUNE. */
	snapshots_pruned: number,
};

/**  Execution history audit entry for a retention pruning run. */
export type RetentionHistoryDto = {
	/**  Unique history identifier. */
	history_id: string,
	/**  Associated backup profile identifier. */
	profile_id: string,
	/**  Timestamp of execution. */
	executed_at: string,
	/**  Whether this was a dry-run execution. */
	dry_run: boolean,
	/**  Total snapshots evaluated. */
	snapshots_evaluated: number,
	/**  Total snapshots kept. */
	snapshots_kept: number,
	/**  Total snapshots pruned. */
	snapshots_pruned: number,
	/**  List of snapshot IDs pruned during this run. */
	pruned_snapshot_ids: string[],
	/**  Execution status ("completed" or "failed"). */
	status: string,
	/**  Error message if execution failed. */
	error_message: string | null,
};

/**  User-facing representation of a backup profile's retention policy. */
export type RetentionPolicyDto = {
	/**  Associated backup profile identifier. */
	profile_id: string,
	/**  Maximum count of recent snapshots to retain. */
	keep_latest_n: number | null,
	/**  Retention window in seconds. */
	keep_newer_than_secs: number | null,
	/**  Whether the latest successful snapshot is unconditionally preserved. */
	keep_latest_successful: boolean,
	/**  Whether the latest snapshot is unconditionally preserved. */
	keep_latest_always: boolean,
	/**  Whether failed or incomplete snapshots are pruned. */
	prune_failed: boolean,
	/**  Whether completed snapshots with zero files are pruned. */
	prune_empty: boolean,
	/**  Whether this retention policy is actively enabled. */
	enabled: boolean,
};

/**  Comprehensive outcome of a retention operation (dry-run or real execution). */
export type RetentionResultDto = {
	/**  Target backup profile identifier. */
	profile_id: string,
	/**  Timestamp of execution. */
	executed_at: string,
	/**  Whether this was a dry-run evaluation with zero changes applied. */
	dry_run: boolean,
	/**  Detailed retention evaluation report. */
	evaluation: RetentionEvaluationDto,
	/**  List of snapshot IDs that were pruned. */
	pruned_snapshots: string[],
	/**  Total file version records pruned. */
	pruned_versions_count: number,
	/**  Whether the operation succeeded. */
	success: boolean,
	/**  Error message if the operation failed. */
	error_message: string | null,
};

/**  User-facing representation of a recurring backup schedule. */
export type ScheduleDto = {
	/**  Unique schedule identifier. */
	schedule_id: string,
	/**  Associated backup profile identifier. */
	profile_id: string,
	/**  Schedule recurrence type. */
	schedule_type: string,
	/**  Schedule expression string. */
	expression: string,
	/**  Timezone calculation strategy. */
	timezone: string,
	/**  Whether the schedule is currently enabled. */
	enabled: boolean,
	/**  ISO-8601 UTC timestamp of next scheduled execution. */
	next_run_at: string | null,
	/**  ISO-8601 UTC timestamp of last executed run. */
	last_run_at: string | null,
	/**  Execution status from the last run. */
	last_status: string | null,
	/**  Error code if the last run failed. */
	last_error_code: string | null,
	/**  Schedule creation timestamp. */
	created_at: string,
	/**  Schedule last update timestamp. */
	updated_at: string,
};

/**  Execution history record for a scheduled backup run. */
export type ScheduleHistoryDto = {
	/**  Unique execution history record identifier. */
	history_id: string,
	/**  Associated schedule identifier. */
	schedule_id: string,
	/**  Associated profile identifier. */
	profile_id: string,
	/**  Execution start timestamp. */
	started_at: string,
	/**  Execution completion timestamp, if finished. */
	completed_at: string | null,
	/**  Execution status ('completed', 'failed', 'cancelled', 'skipped'). */
	status: string,
	/**  Snapshot identifier if backup completed. */
	snapshot_id: string | null,
	/**  Total files processed. */
	files_processed: number,
	/**  Total payload bytes transferred. */
	bytes_transferred: number,
	/**  Error code if execution failed. */
	error_code: string | null,
	/**  Safe human-readable error message. */
	error_message: string | null,
};

/**  Overall status and health of the scheduler subsystem. */
export type SchedulerStatusDto = {
	/**  Operational status: 'running', 'stopped', 'paused'. */
	status: string,
	/**  Number of configured enabled schedules. */
	active_schedules_count: number,
	/**  Profiles currently executing backups. */
	running_profiles: string[],
};

/**  Parameters for configuring or updating a profile's retention policy. */
export type SetRetentionPolicyRequest = {
	/**  Target backup profile identifier. */
	profile_id: string,
	/**  Maximum count of recent snapshots to retain. */
	keep_latest_n: number | null,
	/**  Retention window in seconds; snapshots newer than this age are kept. */
	keep_newer_than_secs: number | null,
	/**  Whether to unconditionally preserve the latest successful snapshot. */
	keep_latest_successful: boolean | null,
	/**  Whether to unconditionally preserve the latest snapshot regardless of age or status. */
	keep_latest_always: boolean | null,
	/**  Whether failed or incomplete snapshots should be pruned. */
	prune_failed: boolean | null,
	/**  Whether completed snapshots with zero files should be pruned. */
	prune_empty: boolean | null,
	/**  Whether the retention policy is actively enabled. */
	enabled: boolean | null,
};

/**  Historical snapshot metadata record. */
export type SnapshotDto = {
	snapshot_id: string,
	profile_id: string,
	status: string,
	metadata: string | null,
	created_at: string,
};

/**  File item within a specific historical snapshot. */
export type SnapshotFileDto = {
	file_id: string,
	relative_path: string,
	size_bytes: number,
	status: string,
	mime_type: string | null,
};

/**  Result details of a full snapshot directory restore operation. */
export type SnapshotRestoreResultDto = {
	snapshot_id: string,
	target_directory: string,
	total_files: number,
	restored_files: number,
	skipped_files: number,
	failed_files: number,
	total_bytes: number,
	duration_ms: number,
};

/**  Request to initiate a point-in-time snapshot backup for a profile. */
export type StartBackupRequest = {
	/**  Profile identifier to back up. */
	profile_id: string,
	/**  Optional encryption passphrase if profile has encryption enabled. */
	passphrase: string | null,
};

/**  Storage cache and temporary file retention parameters. */
export type StorageConfigDto = {
	/**  Maximum cache size allowed in megabytes. */
	max_cache_size_mb: number,
	/**  Retention period for temporary staging files in hours. */
	temp_retention_hours: number,
};

/**  Standardized resolved system directories managed by PathManager. */
export type SystemPathsDto = {
	/**  Root data directory (e.g. %LOCALAPPDATA%\TELEVAULT). */
	base_dir: string,
	/**  Path to embedded SQLite database. */
	database_path: string,
	/**  Path to temporary payload staging directory. */
	temp_dir: string,
	/**  Path to application logs directory. */
	logs_dir: string,
	/**  Path to application config directory. */
	config_dir: string,
};

/**  Transfer workers and concurrency throttling parameters. */
export type TransferConfigDto = {
	/**  Standard chunk size for file slicing in kilobytes (64 to 32768). */
	chunk_size_kb: number,
	/**  Maximum number of concurrent transfer workers (1 to 16). */
	max_concurrent_transfers: number,
	/**  Maximum upload bandwidth limit in KB/s (0 = unlimited). */
	upload_limit_kbps: number,
};

/**  Snapshot of a transfer job record. */
export type TransferJobDto = {
	job_id: string,
	file_id: string,
	chunk_id: string | null,
	direction: string,
	status: string,
	progress: number,
	retry_count: number,
	error_message: string | null,
	created_at: string,
	updated_at: string,
};

/**  Aggregate summary of transfer engine queues. */
export type TransferStatusDto = {
	active_count: number,
	queued_count: number,
	completed_count: number,
	failed_count: number,
};

/**  Frontend request to modify an existing backup profile. */
export type UpdateProfileRequest = {
	/**  Identifier of the profile to update. */
	profile_id: string,
	/**  New human-friendly label if modifying. */
	name: string | null,
	/**  Optional description if modifying. */
	description: string | null,
	/**  New source directory path if modifying. */
	source_path: string | null,
	/**  Enable or disable profile. */
	enabled: boolean | null,
};

/**  Parameters for updating an existing schedule configuration. */
export type UpdateScheduleRequest = {
	/**  Target schedule identifier. */
	schedule_id: string,
	/**  New schedule type, if updating. */
	schedule_type: string | null,
	/**  New recurrence expression, if updating. */
	expression: string | null,
	/**  New timezone strategy, if updating. */
	timezone: string | null,
	/**  New enabled state, if updating. */
	enabled: boolean | null,
};

/**  Structured finding identifying a specific issue discovered during verification. */
export type VerificationFindingDto = {
	level: string,
	severity: string,
	code: string,
	description: string,
	restore_impact: string,
	profile_id: string | null,
	snapshot_id: string | null,
	file_id: string | null,
	chunk_id: string | null,
	chunk_index: number | null,
};

/**  Persisted audit history entry from SQLite verification_history table. */
export type VerificationHistoryRecordDto = {
	history_id: string,
	profile_id: string,
	target_type: string,
	target_id: string,
	level: number,
	status: string,
	is_restore_ready: boolean,
	total_files: number,
	total_manifests: number,
	total_chunks: number,
	healthy_chunks: number,
	missing_chunks: number,
	corrupted_chunks: number,
	ownership_violations: number,
	findings_json: string,
	duration_ms: number,
	verified_at: string,
};

/**  Comprehensive verification audit result for a target object. */
export type VerificationResultDto = {
	target_type: string,
	target_id: string,
	profile_id: string,
	level: string,
	status: string,
	is_restore_ready: boolean,
	findings: VerificationFindingDto[],
	summary: VerificationSummaryDto,
	verified_at: string,
};

/**  Quantitative summary counts of verification results. */
export type VerificationSummaryDto = {
	total_files: number,
	total_manifests: number,
	total_chunks: number,
	healthy_chunks: number,
	missing_chunks: number,
	corrupted_chunks: number,
	ownership_violations: number,
	is_restore_ready: boolean,
	status: string,
	duration_ms: number,
};

/**  Request to verify metadata of a manifest by FileId. */
export type VerifyManifestRequest = {
	file_id: string,
};

/**  Request parameters for scoped remote backup verification. */
export type VerifyTargetRequest = {
	/**  Associated profile identifier enforcing ownership isolation. */
	profile_id: string,
	/**  Target identifier (file_id, manifest_id, or snapshot_id depending on command). */
	target_id: string | null,
	/**  Verification scope level: 1 (MetadataOnly), 2 (RemoteAvailability), 3 (RemoteIntegrity), 4 (RestoreReadiness). */
	level: number | null,
	/**  Whether to force streaming byte integrity hash calculation. */
	full_hash_check: boolean | null,
	/**  Whether to attempt decryption and authentication verification. */
	decrypt_check: boolean | null,
	/**  Optional operation tracking identifier for cooperative cancellation. */
	operation_id: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

