[package]
name = "televault-crypto"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
televault-core = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
aes-gcm = { workspace = true }
argon2 = { workspace = true }
zeroize = { workspace = true }
rand = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
