[package]
name = "televault-backup"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
televault-core = { workspace = true }
televault-crypto = { workspace = true }
televault-manifest = { workspace = true }
televault-storage = { workspace = true }
televault-transfer = { workspace = true }
televault-db = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
chrono = { workspace = true }

